version: "3"

services:
  bot:
    image: catalogger
    build: .
    command: ["/app/catalogger", "bot"]
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@postgres/postgres"
      - "REDIS=redis:6379"
    volumes:
      - "./.env:/app/.env:ro"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - default

  dashboard:
    image: catalogger
    command: ["/app/catalogger", "web"]
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@postgres/postgres"
      - "REDIS=redis:6379"
      - "PORT=:5000"
      - "RPC_HOST=bot:50051"
    volumes:
      - "./.env:/app/.env:ro"
    ports:
      - "127.0.0.1:2838:5000"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - bot
    networks:
      - default

  postgres:
    image: postgres:13-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    command: ["postgres",
              "-c", "max-connections=1000",
              "-c", "timezone=Etc/UTC",
              "-c", "max_wal_size=1GB",
              "-c", "min_wal_size=80MB",
              "-c", "shared_buffers=128MB"]
    environment:
      - "POSTGRES_PASSWORD=postgres"
    restart: unless-stopped
    networks:
      - default

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
