// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/guild_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildChannel_ChannelType int32

const (
	GuildChannel_UNKNOWN  GuildChannel_ChannelType = 0
	GuildChannel_TEXT     GuildChannel_ChannelType = 1
	GuildChannel_NEWS     GuildChannel_ChannelType = 2
	GuildChannel_CATEGORY GuildChannel_ChannelType = 3
	GuildChannel_VOICE    GuildChannel_ChannelType = 4
	GuildChannel_THREAD   GuildChannel_ChannelType = 5
)

// Enum value maps for GuildChannel_ChannelType.
var (
	GuildChannel_ChannelType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXT",
		2: "NEWS",
		3: "CATEGORY",
		4: "VOICE",
		5: "THREAD",
	}
	GuildChannel_ChannelType_value = map[string]int32{
		"UNKNOWN":  0,
		"TEXT":     1,
		"NEWS":     2,
		"CATEGORY": 3,
		"VOICE":    4,
		"THREAD":   5,
	}
)

func (x GuildChannel_ChannelType) Enum() *GuildChannel_ChannelType {
	p := new(GuildChannel_ChannelType)
	*p = x
	return p
}

func (x GuildChannel_ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildChannel_ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_info_proto_enumTypes[0].Descriptor()
}

func (GuildChannel_ChannelType) Type() protoreflect.EnumType {
	return &file_proto_guild_info_proto_enumTypes[0]
}

func (x GuildChannel_ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildChannel_ChannelType.Descriptor instead.
func (GuildChannel_ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{7, 0}
}

type GuildUserCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuildUserCountRequest) Reset() {
	*x = GuildUserCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildUserCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildUserCountRequest) ProtoMessage() {}

func (x *GuildUserCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildUserCountRequest.ProtoReflect.Descriptor instead.
func (*GuildUserCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{0}
}

type GuildUserCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildCount int64 `protobuf:"varint,1,opt,name=guild_count,json=guildCount,proto3" json:"guild_count,omitempty"`
	UserCount  int64 `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
}

func (x *GuildUserCountResponse) Reset() {
	*x = GuildUserCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildUserCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildUserCountResponse) ProtoMessage() {}

func (x *GuildUserCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildUserCountResponse.ProtoReflect.Descriptor instead.
func (*GuildUserCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{1}
}

func (x *GuildUserCountResponse) GetGuildCount() int64 {
	if x != nil {
		return x.GuildCount
	}
	return 0
}

func (x *GuildUserCountResponse) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

// user guild list -> filtered guild list with joined info
type UserGuildListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId []uint64 `protobuf:"varint,1,rep,packed,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
}

func (x *UserGuildListRequest) Reset() {
	*x = UserGuildListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGuildListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGuildListRequest) ProtoMessage() {}

func (x *UserGuildListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGuildListRequest.ProtoReflect.Descriptor instead.
func (*UserGuildListRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{2}
}

func (x *UserGuildListRequest) GetGuildId() []uint64 {
	if x != nil {
		return x.GuildId
	}
	return nil
}

type UserGuildListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guilds []*GuildListGuild `protobuf:"bytes,1,rep,name=guilds,proto3" json:"guilds,omitempty"`
}

func (x *UserGuildListResponse) Reset() {
	*x = UserGuildListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGuildListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGuildListResponse) ProtoMessage() {}

func (x *UserGuildListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGuildListResponse.ProtoReflect.Descriptor instead.
func (*UserGuildListResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{3}
}

func (x *UserGuildListResponse) GetGuilds() []*GuildListGuild {
	if x != nil {
		return x.Guilds
	}
	return nil
}

// A single guild in the filtered list. "joined" is true if the bot is a member of the guild, false otherwise.
type GuildListGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Joined bool   `protobuf:"varint,2,opt,name=joined,proto3" json:"joined,omitempty"`
}

func (x *GuildListGuild) Reset() {
	*x = GuildListGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildListGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildListGuild) ProtoMessage() {}

func (x *GuildListGuild) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildListGuild.ProtoReflect.Descriptor instead.
func (*GuildListGuild) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{4}
}

func (x *GuildListGuild) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildListGuild) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

type GuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GuildRequest) Reset() {
	*x = GuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRequest) ProtoMessage() {}

func (x *GuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRequest.ProtoReflect.Descriptor instead.
func (*GuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{5}
}

func (x *GuildRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// A stripped-down discord.Guild object
type GuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon     string          `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Channels []*GuildChannel `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *GuildResponse) Reset() {
	*x = GuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildResponse) ProtoMessage() {}

func (x *GuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildResponse.ProtoReflect.Descriptor instead.
func (*GuildResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{6}
}

func (x *GuildResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GuildResponse) GetChannels() []*GuildChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

// A stripped-down discord.Channel object
type GuildChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId uint64                   `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name       string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position   int32                    `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Type       GuildChannel_ChannelType `protobuf:"varint,5,opt,name=type,proto3,enum=GuildChannel_ChannelType" json:"type,omitempty"`
}

func (x *GuildChannel) Reset() {
	*x = GuildChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildChannel) ProtoMessage() {}

func (x *GuildChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildChannel.ProtoReflect.Descriptor instead.
func (*GuildChannel) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{7}
}

func (x *GuildChannel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildChannel) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GuildChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildChannel) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *GuildChannel) GetType() GuildChannel_ChannelType {
	if x != nil {
		return x.Type
	}
	return GuildChannel_UNKNOWN
}

type ClearCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId    uint64   `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ChannelIds []uint64 `protobuf:"varint,2,rep,packed,name=channel_ids,json=channelIds,proto3" json:"channel_ids,omitempty"`
}

func (x *ClearCacheRequest) Reset() {
	*x = ClearCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheRequest) ProtoMessage() {}

func (x *ClearCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{8}
}

func (x *ClearCacheRequest) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *ClearCacheRequest) GetChannelIds() []uint64 {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

type ClearCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ClearCacheResponse) Reset() {
	*x = ClearCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_guild_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheResponse) ProtoMessage() {}

func (x *ClearCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_info_proto_rawDescGZIP(), []int{9}
}

func (x *ClearCacheResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClearCacheResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_guild_info_proto protoreflect.FileDescriptor

var file_proto_guild_info_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x58, 0x0a, 0x16, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x14, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x40,
	0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x06, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x73,
	0x22, 0x38, 0x0a, 0x0e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x0d, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0xf3,
	0x01, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x53, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x45, 0x57, 0x53, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x48, 0x52, 0x45,
	0x41, 0x44, 0x10, 0x05, 0x22, 0x4f, 0x0a, 0x11, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x3a, 0x0a, 0x12, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0xf4, 0x01, 0x0a, 0x10, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12,
	0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x12, 0x2e, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x73, 0x68, 0x69, 0x6e, 0x65,
	0x2d, 0x73, 0x79, 0x73, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f,
	0x77, 0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_guild_info_proto_rawDescOnce sync.Once
	file_proto_guild_info_proto_rawDescData = file_proto_guild_info_proto_rawDesc
)

func file_proto_guild_info_proto_rawDescGZIP() []byte {
	file_proto_guild_info_proto_rawDescOnce.Do(func() {
		file_proto_guild_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_guild_info_proto_rawDescData)
	})
	return file_proto_guild_info_proto_rawDescData
}

var file_proto_guild_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_guild_info_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_guild_info_proto_goTypes = []interface{}{
	(GuildChannel_ChannelType)(0),  // 0: GuildChannel.ChannelType
	(*GuildUserCountRequest)(nil),  // 1: GuildUserCountRequest
	(*GuildUserCountResponse)(nil), // 2: GuildUserCountResponse
	(*UserGuildListRequest)(nil),   // 3: UserGuildListRequest
	(*UserGuildListResponse)(nil),  // 4: UserGuildListResponse
	(*GuildListGuild)(nil),         // 5: GuildListGuild
	(*GuildRequest)(nil),           // 6: GuildRequest
	(*GuildResponse)(nil),          // 7: GuildResponse
	(*GuildChannel)(nil),           // 8: GuildChannel
	(*ClearCacheRequest)(nil),      // 9: ClearCacheRequest
	(*ClearCacheResponse)(nil),     // 10: ClearCacheResponse
}
var file_proto_guild_info_proto_depIdxs = []int32{
	5,  // 0: UserGuildListResponse.guilds:type_name -> GuildListGuild
	8,  // 1: GuildResponse.channels:type_name -> GuildChannel
	0,  // 2: GuildChannel.type:type_name -> GuildChannel.ChannelType
	3,  // 3: GuildInfoService.UserGuildList:input_type -> UserGuildListRequest
	6,  // 4: GuildInfoService.Guild:input_type -> GuildRequest
	9,  // 5: GuildInfoService.ClearCache:input_type -> ClearCacheRequest
	1,  // 6: GuildInfoService.GuildUserCount:input_type -> GuildUserCountRequest
	4,  // 7: GuildInfoService.UserGuildList:output_type -> UserGuildListResponse
	7,  // 8: GuildInfoService.Guild:output_type -> GuildResponse
	10, // 9: GuildInfoService.ClearCache:output_type -> ClearCacheResponse
	2,  // 10: GuildInfoService.GuildUserCount:output_type -> GuildUserCountResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_guild_info_proto_init() }
func file_proto_guild_info_proto_init() {
	if File_proto_guild_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_guild_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildUserCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildUserCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGuildListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGuildListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildListGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_guild_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_guild_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_guild_info_proto_goTypes,
		DependencyIndexes: file_proto_guild_info_proto_depIdxs,
		EnumInfos:         file_proto_guild_info_proto_enumTypes,
		MessageInfos:      file_proto_guild_info_proto_msgTypes,
	}.Build()
	File_proto_guild_info_proto = out.File
	file_proto_guild_info_proto_rawDesc = nil
	file_proto_guild_info_proto_goTypes = nil
	file_proto_guild_info_proto_depIdxs = nil
}
